cut_body_after = "" # don't include text from the PR body in the merge commit message
status = [
  "Evaluate flake.nix",
  "Linting (fmt + clippy)",
  "check envfsCrossAarch64 [x86_64-linux]",
  "check integration-tests [x86_64-linux]",
  "package default [x86_64-linux]",
  "package envfs [x86_64-linux]",
  "package envfsStatic [x86_64-linux]"
]
